// <auto-generated />
namespace Mettal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changecolumntypeis___inproductschema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changecolumntypeis___inproductschema));
        
        string IMigrationMetadata.Id
        {
            get { return "201610011415101_change-column-type-is___-in-product-schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
