// <auto-generated />
namespace Mettal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addordernumbertoproductschema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addordernumbertoproductschema));
        
        string IMigrationMetadata.Id
        {
            get { return "201610011316389_add-order-number-to-product-schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
